<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Discussion Panel</name>
   <tag></tag>
   <elementGuidId>c12e22f6-905b-4fb8-8e0a-ce0e9c8043e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'flex h-full flex-col overflow-hidden bg-background') and .//label[contains(text(), 'Discussion')]]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.h-12.min-h-12.w-full.items-center.gap-2.pr-2.pl-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aecd365e-c38e-4c1b-99c3-aed9fb0abd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-12 min-h-12 w-full items-center gap-2 pr-2 pl-3</value>
      <webElementGuid>489bf1b6-cd59-4ded-8816-d7e7b5507558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Discussion</value>
      <webElementGuid>2a37dfc1-f977-484d-9a26-cb1e948542f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_r_73_&quot;)/div[@class=&quot;flex h-full flex-col overflow-hidden bg-background&quot;]/div[@class=&quot;flex h-12 min-h-12 w-full items-center gap-2 pr-2 pl-3&quot;]</value>
      <webElementGuid>2bf4278d-d2dc-49ae-a247-f73a1ac63340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_r_73_']/div[2]/div</value>
      <webElementGuid>b1051715-a830-485c-b79b-162fe08e5ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::div[5]</value>
      <webElementGuid>43b770c6-9fc1-429e-ba4e-3e2bd2468b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::div[9]</value>
      <webElementGuid>da2918d6-cd63-4dad-a52d-59c9fa76d6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lieucao16122003'])[4]/preceding::div[4]</value>
      <webElementGuid>2dde6a95-ab4d-4499-a5d6-fca87d2bf0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>6fab8f65-ba10-4b3c-8338-98619f3cc910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Discussion' or . = 'Discussion')]</value>
      <webElementGuid>f7667cbc-f775-4569-98e4-9bd9ced49365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
