<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dialog_confirm leave</name>
   <tag></tag>
   <elementGuidId>095050cd-cadf-4864-b265-fd1a6c568b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radix-_r_2h_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='alertdialog' and @data-slot='alert-dialog-content' and @data-state='open']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e01ca61-93e6-43cd-9cb1-a2cf6df2c529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alertdialog</value>
      <webElementGuid>aae75254-d1f6-4100-873e-75329a041047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_2h_</value>
      <webElementGuid>28dab924-7587-4f0a-97b9-d99aedf01c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radix-_r_2j_</value>
      <webElementGuid>3c0cca17-2c91-49f6-82d6-6dd1e857ba59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-_r_2i_</value>
      <webElementGuid>1cd56568-f5d2-4468-8a4d-f781cf59c50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>27828da6-80c7-4894-babe-43479d74c9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>alert-dialog-content</value>
      <webElementGuid>5566cd03-faa8-4345-97c5-c0b86f57c874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-background data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 fixed top-[50%] left-[50%] z-50 grid w-full max-w-[calc(100%-2rem)] translate-x-[-50%] translate-y-[-50%] rounded-lg border p-6 shadow-lg duration-200 sm:max-w-lg min-w-[300px] gap-5 sm:min-w-[400px] md:min-w-[500px] lg:min-w-[600px]</value>
      <webElementGuid>347fc4e0-a404-4721-bb3c-3061d396d8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7f2a06f2-4c0b-42e4-9abd-0d44bb1cd052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are you absolutely sure?This action cannot be undone. This will permanently remove you from the station AutoTest_1787036806591 and remove all associated data including messages, channels, and member information.Type AutoTest_1787036806591 to confirmCancelLeave Station</value>
      <webElementGuid>f5b4b327-c2d0-43c3-acf6-4b434b6d06bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_2h_&quot;)</value>
      <webElementGuid>d3ec3885-4376-41ca-a38c-c4ee6a7c19a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_2h_']</value>
      <webElementGuid>b9317854-d7d8-436d-bf94-c889e8be58cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[2]</value>
      <webElementGuid>3b354cfb-a3af-46d4-89eb-44c27b897842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>94135967-0021-4045-aab9-dce78b245ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-_r_2h_' and (text() = 'Are you absolutely sure?This action cannot be undone. This will permanently remove you from the station AutoTest_1787036806591 and remove all associated data including messages, channels, and member information.Type AutoTest_1787036806591 to confirmCancelLeave Station' or . = 'Are you absolutely sure?This action cannot be undone. This will permanently remove you from the station AutoTest_1787036806591 and remove all associated data including messages, channels, and member information.Type AutoTest_1787036806591 to confirmCancelLeave Station')]</value>
      <webElementGuid>d8540972-dfe2-48ad-9601-973da53d4232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
