<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send</name>
   <tag></tag>
   <elementGuidId>66ffcc33-9764-420c-ada4-751d121c43f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_r_6m_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[.//*[local-name()='svg' and contains(@class, 'lucide-send-horizontal')] and .//span[text()='Send']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c525e3bb-d2e6-4a4e-a1f2-0b0c56238a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9184bfd0-f231-46a3-bf5d-96f99f888c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer disabled:cursor-not-allowed inline-flex items-center justify-center whitespace-nowrap text-sm font-medium transition-all duration-150 active:scale-[0.97] disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 shrink-0 [&amp;_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive bg-primary text-primary-foreground hover:bg-primary-hover active:bg-primary-active rounded-md gap-1.5 has-[>svg]:px-2.5 h-8 w-8 p-0 mt-auto</value>
      <webElementGuid>aacba449-0f4d-4d8a-8173-b7922e3b7be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_r_6m_</value>
      <webElementGuid>01cd339b-cca2-4000-85fe-5b271b793be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>6bc28bec-dc03-4533-bef4-1fc0269b74f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_r_6m_&quot;)</value>
      <webElementGuid>3927a039-eb1a-48d1-b5c8-a036c2d97c39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='_r_6m_']</value>
      <webElementGuid>5d203771-e479-4b37-9cc2-de6902ba0a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_r_4p_']/div/div[2]/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>3de93bb4-d6ab-4090-b03a-9185b4824a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::button[1]</value>
      <webElementGuid>74ce9161-4e82-4d4f-96bf-d281961e33c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockquote'])[1]/following::button[2]</value>
      <webElementGuid>41911b57-9a9e-48c1-8c96-3f670e82ec4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>1ff10487-bdea-41e4-a202-ffd804347c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '_r_6m_' and (text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>86ba3ac1-2f65-4157-949d-d08e250683ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
