<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mention</name>
   <tag></tag>
   <elementGuidId>f06a524c-f5fb-40ea-abe0-a8daeb74c79b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2654bb2-def0-4131-91d2-ed32260dccdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>tooltip-trigger</value>
      <webElementGuid>bcd5358a-6af3-4aac-b028-ae1bb99278af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer disabled:cursor-not-allowed inline-flex items-center justify-center gap-2 whitespace-nowrap text-sm font-medium transition-all duration-150 active:scale-[0.97] disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 shrink-0 [&amp;_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive hover:bg-accent hover:text-accent-foreground active:bg-accent-active dark:hover:bg-accent/50 dark:active:bg-accent-active size-9 h-7 w-7 rounded-sm</value>
      <webElementGuid>8b51e89d-92ce-4e54-8c61-f674066a2d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3516f1c8-88ac-4829-b01a-0aa61030388e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>c86b4a0a-a570-444f-ab07-4459fec3106d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mention</value>
      <webElementGuid>317e4b55-82a9-4e98-b82e-7e41c58ab7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_r_5b_&quot;)/div[@class=&quot;flex h-full flex-col&quot;]/div[@class=&quot;flex min-h-0 flex-1 flex-col overflow-hidden&quot;]/div[@class=&quot;relative outline-none flex h-full flex-col overflow-hidden bg-background&quot;]/div[@class=&quot;p-2&quot;]/div[@class=&quot;relative flex flex-col rounded-2xl border bg-card transition-all focus-within:border-ring/40&quot;]/div[@class=&quot;@container relative flex flex-1 flex-col&quot;]/div[@class=&quot;no-scrollbar justify-start border-b-0 bg-transparent p-2 pb-1 flex @md:flex-row flex-col items-start @md:items-center @md:gap-0 gap-1 overflow-hidden&quot;]/div[@class=&quot;flex w-full min-w-0 items-center gap-0.5 overflow-hidden @md:w-full max-w-full flex-1&quot;]/div[@class=&quot;flex shrink-0 items-center&quot;]/button[@class=&quot;cursor-pointer disabled:cursor-not-allowed inline-flex items-center justify-center gap-2 whitespace-nowrap text-sm font-medium transition-all duration-150 active:scale-[0.97] disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 shrink-0 [&amp;_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive hover:bg-accent hover:text-accent-foreground active:bg-accent-active dark:hover:bg-accent/50 dark:active:bg-accent-active size-9 h-7 w-7 rounded-sm&quot;]</value>
      <webElementGuid>c1063f57-e8c8-4707-ba7c-3cb73877c3f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>f275d86b-040b-4d64-99a3-1156b0edb906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_r_5b_']/div/div[2]/div/div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>572dbd7c-06ad-4f23-b67a-db991f5f42c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add member'])[1]/following::button[4]</value>
      <webElementGuid>3a15858d-d183-4ab0-b5d3-9afaddf1905d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lieucao16122003'])[2]/following::button[5]</value>
      <webElementGuid>37681f58-d24b-4606-9ed3-e2bdbf738ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emoji'])[1]/preceding::button[1]</value>
      <webElementGuid>22da1963-a00c-4d83-8381-fd7628d30b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>a27d772c-48ee-4c12-8419-d7c138ef2f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Mention' or . = 'Mention')]</value>
      <webElementGuid>f679126b-615c-4ed5-9503-4438a6791c5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
