<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mention-Suggestions</name>
   <tag></tag>
   <elementGuidId>671b86a4-3606-4afb-a6a9-009226ba81e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@aria-label='Suggestions' and @data-selector='tiptap-mention-dropdown-menu' and @role='listbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65c6040d-ed1a-46cf-9877-4acea5a8a498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>535e3cbd-dce0-4559-8f8f-be246eeb677c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>command</value>
      <webElementGuid>a1f6a7db-be33-46fb-b93a-190eea7a70c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-popover text-popover-foreground flex h-full flex-col overflow-hidden w-64 min-w-40 max-w-[min(16rem,calc(100vw-2rem))] rounded-lg border shadow-md</value>
      <webElementGuid>e1746a95-1d41-40e3-917c-a928b60316e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Everyonelieucao16122003</value>
      <webElementGuid>abd0e462-2098-40c9-a5c2-2a195387e7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_r_77_&quot;)/div[@class=&quot;tiptap-suggestion-menu&quot;]/div[@class=&quot;bg-popover text-popover-foreground flex h-full flex-col overflow-hidden w-64 min-w-40 max-w-[min(16rem,calc(100vw-2rem))] rounded-lg border shadow-md&quot;]</value>
      <webElementGuid>8620e860-eb53-494c-92d4-3acf7cb28a33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_r_77_']/div/div</value>
      <webElementGuid>cea5047b-1c09-4a95-950e-8703f41fc690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>0cf08928-819d-4e26-bf32-e5ef1197be42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>bfb577eb-0a64-4ed6-9a88-7f647af033fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Everyonelieucao16122003' or . = 'Everyonelieucao16122003')]</value>
      <webElementGuid>14dd4c56-1835-44ad-9745-e45b3a348281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
