<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enable</name>
   <tag></tag>
   <elementGuidId>a8238f50-e90a-40dc-85c1-2c72f871010c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@data-sonner-toast]//button[contains(text(), 'Enable')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c8a3945-b77b-4eab-a65e-f1ed55f8f26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e51d668b-732e-4716-95c0-d06a6b448030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer disabled:cursor-not-allowed inline-flex items-center justify-center whitespace-nowrap text-sm font-medium transition-all duration-150 active:scale-[0.97] disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 shrink-0 [&amp;_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive bg-primary text-primary-foreground hover:bg-primary-hover active:bg-primary-active h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5</value>
      <webElementGuid>b1e01a6c-4ea4-4cdf-bec1-8e66145681e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enable</value>
      <webElementGuid>e7998532-b336-4ee5-82bf-6a3fe3b3b8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[1]/ol[@class=&quot;toaster group&quot;]/li[1]/div[1]/div[1]/div[@class=&quot;flex min-w-[320px] max-w-105 items-start gap-3 rounded-lg border bg-background p-4 shadow-lg&quot;]/div[@class=&quot;min-w-0 flex-1&quot;]/div[@class=&quot;flex gap-2&quot;]/button[@class=&quot;cursor-pointer disabled:cursor-not-allowed inline-flex items-center justify-center whitespace-nowrap text-sm font-medium transition-all duration-150 active:scale-[0.97] disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 shrink-0 [&amp;_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive bg-primary text-primary-foreground hover:bg-primary-hover active:bg-primary-active h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5&quot;]</value>
      <webElementGuid>6a884989-5770-47a0-b34c-ab5bd0f8e26e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/ol/li/div/div/div/div[2]/div/button</value>
      <webElementGuid>0e051420-de07-40f5-8f6d-e2b2eddebd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable notifications?'])[1]/following::button[1]</value>
      <webElementGuid>8c6a7497-1335-40cf-aafa-d9b26e00b4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nihon'])[1]/following::button[2]</value>
      <webElementGuid>8c6d529e-ca2e-4a7b-8d0c-61a33bcdb721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enable']/parent::*</value>
      <webElementGuid>a696d1dc-3c86-497d-8219-9a6f7fdb1ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div[2]/div/button</value>
      <webElementGuid>5319bb68-7354-4883-9585-aa643c81036f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Enable' or . = 'Enable')]</value>
      <webElementGuid>3141e8ba-c368-4d44-8949-85241ab722a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
