<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Noti-Station_Popover</name>
   <tag></tag>
   <elementGuidId>55162b3a-6787-4c78-a0a8-d5dc6bc445db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radix-_r_1q_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='dialog' and @data-slot='popover-content' and @data-state='open' and contains(@class, 'bg-popover')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62e3b529-6e5a-4a4e-a7ed-8b51651505b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-side</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>dc079add-5cd7-476f-846e-e10763518d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-align</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>5eac7152-adc5-41da-bc92-e14d905a0824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>55fb37bf-c3d1-4ff5-8897-0efaec5db3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>073f842d-388b-46a3-b1a2-276773077ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_1q_</value>
      <webElementGuid>4c6341b3-7ba1-4ef8-bef2-83cf7d41ce5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>popover-content</value>
      <webElementGuid>31925019-93a4-4fee-8af1-ceb3e2610fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-popover text-popover-foreground data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 z-50 origin-(--radix-popover-content-transform-origin) rounded-xl border shadow-md outline-hidden overflow-hidden flex max-h-125 w-90 flex-col p-0</value>
      <webElementGuid>55d335d4-5272-40f5-b34f-b7d7731cd346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ab96ee68-f61b-4857-94ce-a6786e61fff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[data-radix-scroll-area-viewport]{scrollbar-width:none;-ms-overflow-style:none;-webkit-overflow-scrolling:touch;}[data-radix-scroll-area-viewport]::-webkit-scrollbar{display:none}lieucao1612200336 minutes agoinvited you to join Station: AutoTest_1787032392056AAutoTest_17870323920561 MembersRejectAcceptlieucao1612200343 minutes agoinvited you to join Station: AutoTest_1787031960336AAutoTest_17870319603361 MembersRejectAcceptMark all as read</value>
      <webElementGuid>0036fdbf-6740-4486-81e6-4eb2caf20312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_1q_&quot;)</value>
      <webElementGuid>67476f7b-506b-4eb8-b17d-2c89ddf2f053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_1q_']</value>
      <webElementGuid>95f7d270-839e-4b23-9889-fab63007467f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[2]</value>
      <webElementGuid>9a5c63a3-7efa-45d5-98af-4ca266e898ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>5dc2f6bf-735f-426e-8a1a-007cbe5ec1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-_r_1q_' and (text() = '[data-radix-scroll-area-viewport]{scrollbar-width:none;-ms-overflow-style:none;-webkit-overflow-scrolling:touch;}[data-radix-scroll-area-viewport]::-webkit-scrollbar{display:none}lieucao1612200336 minutes agoinvited you to join Station: AutoTest_1787032392056AAutoTest_17870323920561 MembersRejectAcceptlieucao1612200343 minutes agoinvited you to join Station: AutoTest_1787031960336AAutoTest_17870319603361 MembersRejectAcceptMark all as read' or . = '[data-radix-scroll-area-viewport]{scrollbar-width:none;-ms-overflow-style:none;-webkit-overflow-scrolling:touch;}[data-radix-scroll-area-viewport]::-webkit-scrollbar{display:none}lieucao1612200336 minutes agoinvited you to join Station: AutoTest_1787032392056AAutoTest_17870323920561 MembersRejectAcceptlieucao1612200343 minutes agoinvited you to join Station: AutoTest_1787031960336AAutoTest_17870319603361 MembersRejectAcceptMark all as read')]</value>
      <webElementGuid>990f39cd-3325-45cc-8491-68da113cc646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
